name = "Testfiles"
uuid = "cbb5340f-90c5-49b5-a6e6-2125e1f2b326"
version = "1.0.0-DEV"
authors = ["Hans Würfel <git@wuerfel.io> and contributors"]

[deps]
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
IOCapture = "1.0.0"
Test = "1.10.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
